platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'Example' do
    pod 'Blaze'
    pod 'BDGMacros'
    
    pod 'TTTAttributedLabel', git: 'https://github.com/kwketh/TTTAttributedLabel'
end
